# Human Tasks:
# 1. Replace <namespace_name> with the actual namespace name for your environment (e.g., workflow-platform)
# 2. Replace <application_label> with your application identifier (e.g., workflow-automation)
# 3. Replace <environment_label> with the deployment environment (e.g., dev, staging, prod)
# 4. Replace <base64_encoded_password> with the base64-encoded database password
# 5. Replace <base64_encoded_api_key> with the base64-encoded API key
# 6. Replace <base64_encoded_tls_certificate> with the base64-encoded TLS certificate
# 7. Replace <base64_encoded_tls_key> with the base64-encoded TLS private key

# Requirement Addressed: Sensitive Data Management
# Location: Technical Specification/Security Architecture/Data Security
# Description: Ensures that sensitive information such as API keys, database credentials, 
# and certificates are securely stored and managed using Kubernetes Secrets.

---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-platform-credentials
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: core
type: Opaque
data:
  DB_PASSWORD: <base64_encoded_password>
  API_KEY: <base64_encoded_api_key>

---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-platform-tls
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: security
type: Opaque
data:
  TLS_CERT: <base64_encoded_tls_certificate>
  TLS_KEY: <base64_encoded_tls_key>

---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-platform-integration
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: integration
type: Opaque
data:
  SHOPIFY_API_KEY: <base64_encoded_api_key>
  SALESFORCE_API_KEY: <base64_encoded_api_key>
  HUBSPOT_API_KEY: <base64_encoded_api_key>
  QUICKBOOKS_API_KEY: <base64_encoded_api_key>

---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-platform-monitoring
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: monitoring
type: Opaque
data:
  DATADOG_API_KEY: <base64_encoded_api_key>
  PROMETHEUS_AUTH_TOKEN: <base64_encoded_api_key>
  GRAFANA_ADMIN_PASSWORD: <base64_encoded_password>