# Human Tasks:
# 1. Replace <namespace_name> with the actual namespace name for your environment
# 2. Replace <application_label> with your application identifier
# 3. Replace <environment_label> with the deployment environment (e.g., dev, staging, prod)
# 4. Replace <service_account_name> with the desired service account name
# 5. Replace <secret_name> with the actual secret name that should be associated with this service account

# Requirement Addressed: Identity and Access Management
# Location: Technical Specification/Security Architecture/Authorization Model
# Description: Ensures that pods and other Kubernetes resources are associated with 
# specific identities and permissions for secure access control.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <service_account_name>
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
  annotations:
    description: "Service account for workflow automation platform components"
secrets:
  - name: <secret_name>

---
# Service account for workflow execution engine
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-engine
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: workflow-engine
  annotations:
    description: "Service account for workflow execution engine pods"
secrets:
  - name: <secret_name>

---
# Service account for API server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: api-server
  annotations:
    description: "Service account for API server pods"
secrets:
  - name: <secret_name>

---
# Service account for task workers
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-worker
  namespace: <namespace_name>
  labels:
    app: <application_label>
    environment: <environment_label>
    component: task-worker
  annotations:
    description: "Service account for task worker pods"
secrets:
  - name: <secret_name>